version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      expo:
        patterns:
          - "expo"
          - "expo-*"
          - "@expo/*"
      react-native:
        patterns:
          - "react-native"
          - "@react-native*"
      babel:
        patterns:
          - "@babel/*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
