blank_issues_enabled: true
contact_links:
  - name: Secret Hitler (original game)
    url: https://www.secrethitler.com/
    about: This is an unofficial fan adaptation. For the official game, visit here.
